# Generated by Django 2.2.3 on 2022-01-14 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contas', '0002_auto_20220114_1919'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoReceita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_receita', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da Receita')),
                ('data_recebimento', models.DateField()),
                ('data_recebimento_esperado', models.DateField()),
                ('conta_receita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contas.Conta', verbose_name='Conta Vinculada')),
                ('tipo_receita', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='receitas.TipoReceita')),
            ],
        ),
    ]
