# Generated by Django 2.2.3 on 2022-01-16 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_auto_20220114_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='saldo',
            field=models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Saldo'),
        ),
    ]
