# Generated by Django 2.2.3 on 2022-01-14 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDespesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_despesa', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Despesa')),
                ('data_pagamento', models.DateField()),
                ('data_pagamento_esperado', models.DateField()),
                ('conta_despesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contas.Conta')),
                ('tipo_despesa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='despesas.TipoDespesa')),
            ],
        ),
    ]
