# Generated by Django 2.2.3 on 2022-01-14 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='conta_despesa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contas.Conta', verbose_name='Conta Vinculada'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da Despesa'),
        ),
    ]
